- frontend/src/services/Utils.js
Adicionando validação no método onlyNumbers
> Adicionando validação no método onlyNumbers

- backend/src/db/migrations/20200416140357-alterando-nome-tabela-notificacao-historico.js
- backend/src/mapper/notificacao-mapper/index.js
- backend/src/mapper/notificacao-mapper/model-para-response.js
- backend/src/mapper/notificacao-mapper/request-para-model.js
- backend/src/models/notificacao.js
- backend/src/models/notificacaoCovid19.js
- backend/src/resource/notificacao-resource.js
Conforme alinhado, iremos alterar o nome da tabela NotificacaoHistorico para NotificacaoCovid19
> Alteração no nome da tabela Notificacao Historico

- frontend/src/App.vue
- frontend/src/components/Notificacao/Form/Comorbidades/index.vue
- frontend/src/components/Notificacao/Form/ConclusaoAtendimento/index.vue
- frontend/src/components/Notificacao/Form/IdentificacaoCaso/index.vue
- frontend/src/components/Notificacao/Form/IdentificacaoNotificante/index.vue
- frontend/src/components/Notificacao/Form/InformacoesComplementares/index.vue
- frontend/src/components/Notificacao/Form/Observacoes/index.vue
- frontend/src/components/Notificacao/Form/RealizadoColeta/index.vue
- frontend/src/components/Notificacao/Form/SinaisESintomas/index.vue
- frontend/src/components/Notificacao/Form/VinculoEpidemiologico/index.vue
- frontend/src/entities/Notificacao.js
- frontend/src/entities/Profissao.js
- frontend/src/views/NotificacaoForm.vue
Criado nova seção e reordenado as seções existentes na tela de notificação. Os dados dos dropdownlist da nova seção estão mockados. Futuramente deverá ser feito a integração com o backend para poder retornar a Unidade Notificadora do usuário logado (informações relacionada com as tabelas unidadesaude, UnidadeSaude_User, user) e as opções de Profissão para o Notificador (informações relacionada com a tabela Profissão [ainda deve ser criada essa tabela]).
> Criado nova seção na tela de notificação

- frontend/src/components/Notificacao/Form/IdentificacaoCaso/DadosPessoais.vue
- frontend/src/components/Notificacao/Form/IdentificacaoNotificante/index.vue
- frontend/src/views/NotificacaoForm.vue
Alterado chamada do update dos dados de Identificação Notificante e começando a criar novos inputs na seção de Identificação do Caso Suspeito
> Alterado chamada do update dos dados de Identificação Notificante

- frontend/src/components/Notificacao/Form/IdentificacaoCaso/DadosPessoais.vue
- frontend/src/entities/Pessoa.js
- frontend/src/views/NotificacaoForm.vue
Implementado update para novos campos (gestante e raça/cor) da Identificação caso suspeito
> Implementado update para novos campos da Identificação caso

- frontend/src/components/Notificacao/Form/IdentificacaoCaso/DadosPessoais.vue
- frontend/src/components/Notificacao/Form/IdentificacaoCaso/index.vue
Correção dos updates sobre gestante e raça/cor
> Correção dos updates sobre gestante e raça/cor

- frontend/src/components/Notificacao/Form/IdentificacaoCaso/Endereco.vue
- frontend/src/components/Notificacao/Form/SinaisESintomas/SinaisSintomas.vue
- frontend/src/components/Notificacao/Form/SinaisESintomas/index.vue
- frontend/src/services/DateService.js
- frontend/src/validations/CommonValidations.js
- frontend/src/validations/__tests__/CommonValidations.spec.js
Alteração geral na seção de Sinais e Sintomas: Agora todos os sinais e sintomas vão ficar juntos. Não removi os componentes existentes (OutrosSintomas.vue, SintomasGerais.vue, SintomasRespiratoriosGraves.vue e SintomasRespiratoriosLeves.vue), mas eles não estão mais sendo usados.
> Alteração geral na seção de Sinais e Sintomas

- backend/src/db/migrations/20200416184430-adicionando-campos-pessoa.js
- backend/src/models/pessoa.js
- backend/src/resource/notificacao-resource.js
Campos gestante e cor/raca adicionados a tabela de Pessoa
> Adicionando campos na tabela pessoa

- frontend/src/components/Notificacao/Form/ExamesImagem/RaioTorax.vue
- frontend/src/components/Notificacao/Form/ExamesImagem/TomografiaTorax.vue
- frontend/src/components/Notificacao/Form/ExamesImagem/index.vue
- frontend/src/components/Notificacao/Form/IdentificacaoNotificante/index.vue
- frontend/src/components/Notificacao/Form/SinaisESintomas/OutrosSintomas.vue
- frontend/src/components/Notificacao/Form/SinaisESintomas/SintomasRespiratorios.vue
- frontend/src/components/Notificacao/Form/SinaisESintomas/index.vue
- frontend/src/entities/ExamesImagem.js
- frontend/src/entities/Notificacao.js
- frontend/src/services/ProfissaoService.js
- frontend/src/validations/CommonValidations.js
- frontend/src/views/NotificacaoForm.vue
Criado nova seção de dados (5. Realizou exame de imagem) e correção do bug encontrado no input de profissão
> Criado nova seção de dados e correção da profissão

- backend/src/db/migrations/20200418143706-create-notificacao-evolucao.js
- backend/src/models/notificacao.js
- backend/src/models/notificacaoEvolucao.js
> model NotificacaoEvolucao

- backend/src/resource/notificacao-resource.js
- backend/src/routes/notification-route.js
> consulta de evolução

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/pull_request_template.md
Adiciona templates para:
- Feature request (Issue)
- Bug Report (Issue)
- Pull Request
> Adicionar templates

- backend/src/resource/notificacao-resource.js
- backend/src/routes/notification-route.js
* [S ] Você atualizou o [Trello](https://trello.com/b/l6D5ec9h/db1-viewer)?
* [ S] Verificou se não há outro [Pull Requests](../../../pulls) aberto para a mesma alteração?
1. [ S] Sua submissão passou nos testes?
2. [ S] Seu código está de acordo com o lint do projeto?
3. [ S] Ainda é possível fazer/desfazer todos os migrates e seeds?
4. [ N] Você criou novos testes para o código escrito?
5. [ S] Os testes foram rodados e passaram localmente?
----------------------------------------------
Regras implementadas:
Situações possíveis para o tipo (tp_evolucao):  
SUSPEITO: São todos os que foram notificados.  
CONFIRMADO: Foi feito o teste e deu positivo 
DESCARTADO: Fez o teste e deu negativo ou chegou à conclusão que é outra doença. 
CURA: Foi confirmado e foi curado; 
ENCERRADO: Não fez o …
> Salvar evolucao

- backend/src/models/profissao.js
- backend/src/resource/profissao-resource.js
- backend/src/routes/profissao-route.js
> Readiciona a feature de profissões fixed #88

- backend/src/validations/schemas/profissao.js
> Remove, novamente, a validação do nome fixed #88

- backend/src/db/migrations/20200420124325-adicionando-model-evolucao-resumo.js
- backend/src/db/seeders/20200420125013-evolucao-resumo.js
- backend/src/models/evolucaoResumo.js
- backend/src/resource/fato-evolucao.resource.js
- backend/src/routes/fato-evolucao-route.js
Essa tabela será preenchida manualmente no início.
> Adicionando modelo evolucao resumo

- backend/src/db/migrations/20200420135657-adicionando-model-evolucao-diaria.js
- backend/src/db/seeders/20200420135906-evolucao-diaria.js
- backend/src/models/evolucaoDiaria.js
- backend/src/resource/fato-evolucao-diaria.resource.js
- backend/src/routes/fato-evolucao-route.js
Essa tabela será preenchida manualmente no início.
> Adicionando modelo evolucao diária

- backend/src/models/notificacaoEvolucao.js
- backend/src/resource/notificacao-resource.js
- backend/src/routes/notification-route.js
- frontend/src/components/Notificacao/Consulta/NotificacaoTable/index.vue
- frontend/src/components/Notificacao/Evolucao/Cons.vue
- frontend/src/components/Notificacao/Evolucao/Form.vue
- frontend/src/entities/Evolucao.js
- frontend/src/entities/NotificacaoEvolucao.js
- frontend/src/entities/__tests__/Evolucao.spec.js
- frontend/src/entities/__tests__/NotificacaoEvolucao.spec.js
- frontend/src/router/index.js
- frontend/src/services/DateService.js
- frontend/src/services/EvolucaoService.js
- frontend/src/services/Http.js
- frontend/src/services/NotificacaoService.js
- frontend/src/views/EvolucaoForm.vue
- frontend/src/views/NotificacaoCons.vue
> Evo integracao

- frontend/.env.production
- frontend/src/components/Notificacao/Consulta/NotificacaoTable/index.vue
- frontend/src/components/Notificacao/Evolucao/Form.vue
- frontend/src/services/Http.js
> correção paginação consulta notificação

- frontend/src/components/Notificacao/Form/IdentificacaoCaso/DadosPessoais.vue
- frontend/src/validations/CommonValidations.js
- frontend/src/views/NotificacaoForm.vue
* [] Você criou uma [Issue](https://github.com/db1group/contra-covid19/issues) para esta alteração?
> Correção dos dados pessoais para gestante

- backend/src/validations/i18n.js
- backend/src/validations/validate.js
5. [X] Os testes foram rodados e passaram localmente?
#113
> Não estava retornando a mensagem de validação

- backend/src/db/migrations/20200420202513-criar-campo-notificacao-municipioId.js
- backend/src/mapper/notificacao-mapper/model-para-response.js
- backend/src/mapper/notificacao-mapper/request-para-model.js
- backend/src/models/notificacao.js
- backend/src/resource/notificacao-resource.js
- frontend/package-lock.json
> Feature/criar campo notificao.municipio id closes 83

- frontend/src/App.vue
- frontend/src/components/Notificacao/Consulta/HeaderCons/index.vue
- frontend/src/components/Notificacao/Consulta/NotificacaoTable/index.vue
- frontend/src/plugins/vuetify.js
- frontend/src/router/index.js
- frontend/src/views/Home.vue
> resolved #107 Adicionando home page + mudando cor

- frontend/.env
- frontend/src/components/Notificacao/Form/IdentificacaoCaso/Endereco.vue
- frontend/src/components/Notificacao/Form/InformacoesComplementares/index.vue
- frontend/src/entities/Pessoa.js
- frontend/src/services/BairroService.js
> resolved #116 Marcando Maringá no município

- backend/src/lib/normalizar-texto.js
- backend/src/lib/remover-acentos.js
- backend/src/models/bairro.js
- backend/src/models/pessoa.js
> Feature/salva caixa alta sem acento dados pessoa bairro [closes #121]

- frontend/src/services/DateService.js
- frontend/src/services/__tests__/DateService.spec.js
> fixed #134 ajustando data inválida

- frontend/src/views/NotificacaoForm.vue
> fix #130 mostrando mensagem de erro quando chamada ao back-end falha

- backend/src/resource/profissao-resource.js
- backend/src/routes/profissoes-route.js
- backend/src/validations/schemas/profissao.js
> Feature/criar rota post profissoes [closes #136]

- backend/src/models/notificacao.js
- backend/src/routes/notification-route.js
> Status não vem do front

- backend/src/lib/remover-acentos.js
- backend/src/models/notificacao.js
- backend/src/routes/notification-route.js
> Erro: removerAcentos is not a function

- backend/src/resource/notificacao-resource.js
> fix cadastro de notificação com status aberta

- frontend/src/components/Notificacao/Form/IdentificacaoCaso/DadosPessoais.vue
- frontend/src/components/Notificacao/Form/OutrasInformacoes/index.vue
> Ajustes de erros

- backend/src/models/notificacaoEvolucao.js
> Bugfix/fixes #152 evolucao com data futura

- frontend/src/components/Notificacao/Form/IdentificacaoCaso/DadosPessoais.vue
- frontend/src/validations/CommonValidations.js
- frontend/src/validations/__tests__/CommonValidations.spec.js
> fix #147 máscara de CPF

- frontend/src/components/Notificacao/Form/VinculoEpidemiologico/index.vue
> fix #145 ajuste nos labels de situação

- frontend/src/components/Notificacao/Form/OutrasInformacoes/index.vue
> fix #170 campo explicitamente obrigatório

- backend/src/models/notificacaoEvolucao.js
> Remove detalhes técnicos da validação (fixes #186)

- backend/config/config.js
- backend/src/models/index.js
- backend/src/resource/notificacao-resource.js
- frontend/.env
- frontend/src/main.js
> correção variáveis ambiente e fix search notificacao

- .circleci/config.yml
> Atualizando CI

- frontend/src/components/Notificacao/Form/IdentificacaoNotificante/index.vue
> Correção do loading da Unidade de Saude

- frontend/src/components/Notificacao/Evolucao/Form.vue
- frontend/src/views/EvolucaoForm.vue
- frontend/src/views/NotificacaoCons.vue
> fix remove settimeout evolucao

- frontend/src/views/NotificacaoForm.vue
Rolar o scroll para o topo após salvar notificação
> Rolar o scroll para o topo após salvar notificação

- frontend/src/components/Notificacao/Evolucao/Form.vue
> Correção de label na tela de evolução

- frontend/src/components/Notificacao/Form/ExamesImagem/RaioTorax.vue
- frontend/src/components/Notificacao/Form/ExamesImagem/TomografiaTorax.vue
- frontend/src/components/Notificacao/Form/ExamesImagem/index.vue
Correção da seleção de exame de imagens.
> Correção da seleção de exame de imagens fix/NotificacaoCovid19-Bug#157

- backend/src/resource/notificacao-resource.js
> Correção p não permitir evolução caso confirmado

- frontend/src/components/Notificacao/Form/IdentificacaoCaso/DadosPessoais.vue
> Adicionando mensagem no campo data de nascimento

- frontend/package.json
> Atualizando yarn serve

- backend/src/resource/notificacao-resource.js
> Adicionada validação da data de evolução fixes #200

- frontend/package.json
- frontend/src/components/Notificacao/Consulta/NotificacaoTable/index.vue
- frontend/src/components/commons/ConfirmDialog.vue
> fix #125 Dialog de confirmação de exclusão de notificação

- backend/src/db/seeders/development/20200424162056-add-profissoes.js
- backend/src/db/seeders/prod/20200424162056-add-profissoes.js
- backend/src/db/seeders/qa/20200424162056-add-profissoes.js
> adicionado novas profissões para o notificador

- backend/src/models/notificacaoCovid19.js
> fixes #194 - Validar data Notificação maior que data atual

- backend/src/resource/notificacao-resource.js
> fixes #295 - Adicionar ordenacao por status e unidade

- backend/src/db/migrations/20200424182358-adicionando-campo-ocupacaoid-pessoa.js
- backend/src/db/migrations/20200424223213-alterar-notificacaoCovid19-dataInicioSintomas-DATEONLY.js
- backend/src/models/notificacaoCovid19.js
> Bugfix/data inicio sintomas data futura fixes #204

- backend/src/resource/notificacao-resource.js
> Fixes #291 - Adicionar nova restrição para status confirmado

- frontend/src/components/Notificacao/Consulta/NotificacaoTable/index.vue
- frontend/src/components/Notificacao/Evolucao/Cons.vue
- frontend/src/entities/NotificacaoConsulta.js
- frontend/src/entities/NotificacaoEvolucao.js
- frontend/src/entities/__tests__/Evolucao.spec.js
- frontend/src/entities/__tests__/NotificacaoEvolucao.spec.js
- frontend/src/entities/__tests__/NotificacaoEvolucao2.spec.js
- frontend/src/services/DateService.js
- frontend/src/views/EvolucaoForm.vue
> fix #149 Arrumando datas para formato GMT-3

- frontend/src/views/NotificacaoForm.vue
> fix #289 reload na pagina após salvar ficha

- backend/config/config.js
> Reintroduzir configurações de utc gmt

- frontend/src/entities/NotificacaoEvolucao.js
- frontend/src/services/DateService.js
> Ajuste gmt-3

- frontend/src/components/Notificacao/Consulta/NotificacaoTable/index.vue
> desabilitado botão evolução notificacao encerrada

- backend/src/resource/notificacao-resource.js
- frontend/.env.dev
- frontend/src/entities/Evolucao.js
- frontend/src/entities/__tests__/Evolucao.spec.js
- frontend/src/entities/__tests__/NotificacaoEvolucao.spec.js
- frontend/src/entities/__tests__/NotificacaoEvolucao2.spec.js
> corrigido para mostrar um dos telefones na evolução

- backend/src/models/notificacaoCovid19.js
> Descomentado campo, não ocorreu mais erro 213

- backend/src/resource/notificacao-resource.js
- frontend/src/components/Notificacao/Consulta/NotificacaoTable/index.vue
- frontend/src/services/NotificacaoService.js
> criado filtro de situacão tela de consulta

- frontend/src/components/Notificacao/Form/IdentificacaoCaso/Endereco.vue
- frontend/src/components/Notificacao/Form/IdentificacaoNotificante/index.vue
> fix loading cadastro notificacao

- backend/src/db/migrations/20200424223213-alterar-notificacaoCovid19-dataInicioSintomas-DATEONLY.js
> #320 - Resolvendo migration que altera campo para not-null

- frontend/.env.dev
- frontend/src/configuration.js
- frontend/src/hotjar.js
- frontend/src/main.js
> closed #160 Adicionando hotjar somente para ambiente de produção

- backend/Dockerfile
- backend/entrypoint.sh
> #323 - Atualizando execução de migrations

- frontend/src/components/Notificacao/Form/ConclusaoAtendimento/index.vue
> #296 - Adicionando obrigatoriedade da situação da notificação

- frontend/src/components/Notificacao/Form/RealizadoColeta/index.vue
> #308 - Atualizando label do nome do laboratório

- backend/src/db/migrations/20200425222300-alterar-campo-tipoLaboratorio-para-nullable.js
> Corrigido campo tipoLaboratorio para nullable #331

- backend/src/db/migrations/20200425192613-alterar-noficacaoCovid19-metodoDeExame-string16.js
- backend/src/models/notificacaoCovid19.js
> Feature/incluir novos tipos metodo exames closes #256

- backend/src/models/notificacaoEvolucao.js
> Adicionar ponto final na mensagem e alterar tipo.

- frontend/src/hotjar.js
> Hotjar agora vai

- frontend/src/entities/Notificacao.js
> Desimpedindo homologação

- backend/src/validations/i18n.js
- backend/src/validations/schemas/notificacao.js
> Bugfix/tornar data inicio dos sintomas nao obrigatorio fixes #347

- frontend/src/components/Notificacao/Form/RealizadoColeta/index.vue
- frontend/src/views/NotificacaoForm.vue
> fix #324 campo era mandado sempre como false para o back-end

- backend/src/db/migrations/20200426184013-alterar-campo-notificacaoCovid19-nomeTeveContato-120char.js
- backend/src/validations/i18n.js
- backend/src/validations/schemas/notificacao.js
> Bugfix/fixes #344 revisar vinculo epidemiologico

- backend/src/db/migrations/20200425225013-alterar-campo-notificacao-nomeNotificador-80char.js
- backend/src/db/migrations/20200426171113-alterar-notificacaoCovid19-dataDaColeta-DATEONLY.js
- backend/src/validations/schemas/notificacao.js
> Bugfix/fixes #345 revistar objeto conclusao atendimento 

- backend/src/db/migrations/20200426230713-alterar-campo-notificacaoCovid19-nomeMedicacoes.js
- backend/src/models/notificacaoCovid19.js
- backend/src/resource/notificacao-resource.js
- backend/src/validations/schemas/notificacao.js
> closes #343 revisar campos objeto informacao complementar

- backend/src/validations/schemas/notificacao.js
> fixes #342 Adicionar validação no objeto request examesImagem

- backend/src/db/migrations/20200427194013-alterar-campo-pessoa-dataDeNascimento-DATEONLY.js
- backend/src/db/migrations/20200427211113-alterar-campo-notificacaoCovid19-raioxXConsolidacao-corrigirNome.js
- backend/src/mapper/notificacao-mapper/index.js
- backend/src/mapper/notificacao-mapper/model-para-response.js
- backend/src/mapper/notificacao-mapper/request-para-model.js
- backend/src/models/notificacaoCovid19.js
- backend/src/models/pessoa.js
- backend/src/validations/schemas/pessoa.js
> fixes #350 erro data de nascimento

- backend/src/resource/fato-evolucao-bairro-resource.js
- backend/src/resource/fato-evolucao-diaria-resource.js
> Adicionando ordenações nas api's de resumo

- frontend/src/App.vue
- frontend/src/hotjar.js
> fix #303 direcionamento após logout

- backend/src/mapper/notificacao-mapper/request-para-model.js
> Corrigido mapeamento do campo sintomatico #366

- frontend/src/components/Notificacao/Evolucao/Form.vue
> fix #305 Habilitando regra de required somente na submissão do form

- frontend/src/components/Notificacao/Form/IdentificacaoCaso/DadosPessoais.vue
> Adicionando regra para validação de obrigatoriedade

- frontend/src/components/Notificacao/Form/VinculoEpidemiologico/index.vue
> Deixando fixo as informações de tipo de notificação

- frontend/src/entities/Pessoa.js
> Arrumado montagem do request para campo pessoa #392

- frontend/src/entities/Notificacao.js
> corrigido visualização sem ser sintomático

- frontend/src/components/Notificacao/Form/IdentificacaoCaso/Endereco.vue
> validado complemento no bairro GERAL

- frontend/src/components/Notificacao/Form/SinaisESintomas/OutrosSintomas.vue
- frontend/src/components/Notificacao/Form/SinaisESintomas/index.vue
- frontend/src/entities/Sintomas.js
- frontend/src/views/NotificacaoForm.vue
> fix #380 Correção do nome do campo

- frontend/src/entities/Comorbidades.js
- frontend/src/entities/ConclusaoAtendimento.js
- frontend/src/entities/InformacoesComplementares.js
- frontend/src/entities/Notificacao.js
- frontend/src/entities/Pessoa.js
- frontend/src/services/DateService.js
- frontend/src/services/Utils.js
- frontend/src/views/NotificacaoForm.vue
> fix #339 Ajustando máscara de campos

- backend/src/validations/i18n.js
- backend/src/validations/schemas/notificacao.js
> Bugfix/fixes #340 revisar objeto sintomas

- frontend/src/entities/Notificacao.js
- frontend/src/entities/Sintomas.js
> Corrigido para não mandar o campo temperaturaFebre com string vazia #411

- backend/src/resource/user-resource.js
- backend/src/routes/users-route.js
- backend/src/validations/schemas/user.js
- frontend/src/App.vue
- frontend/src/main.js
- frontend/src/plugins/logged.js
- frontend/src/ready.js
- frontend/src/services/UserService.js
- frontend/src/views/NotificacaoForm.vue
> Vincular usuário logado na notificação

- frontend/src/components/Notificacao/Consulta/NotificacaoTable/index.vue
> Removido seleção lote e corrigido paginação no filtro de status

- frontend/src/components/Notificacao/Consulta/HeaderCons/index.vue
- frontend/src/components/Notificacao/Exportar/Index.vue
- frontend/src/entities/NotificacaoExportar.js
- frontend/src/router/index.js
- frontend/src/services/DateService.js
- frontend/src/services/NotificacaoService.js
- frontend/src/views/NotificacaoExportar.vue
> Adicionando tela para exportação em excel

- frontend/src/components/Notificacao/Exportar/Index.vue
- frontend/src/entities/NotificacaoExportar.js
- frontend/src/router/index.js
- frontend/src/views/NotificacaoExportar.vue
> Corrigido problema de exportar

- backend/.gitignore
- backend/src/resource/notificacao-exportacao-excel-resource.js
5. [X] Os testes foram rodados e passaram localmente?
> Bugfix/corrigir exportacao nome notificador fixes #423

- backend/src/validations/schemas/profissao.js
- frontend/src/services/ProfissaoService.js
> Corrigido requisição profissões

- backend/src/resource/notificacao-resource.js
- frontend/src/components/Notificacao/Evolucao/Cons.vue
- frontend/src/entities/Evolucao.js
- frontend/src/entities/__tests__/Evolucao.spec.js
- frontend/src/main.js
- frontend/src/plugins/document-mask.js
- frontend/src/plugins/phone-mask.js
> Melhorias visualização evolução, criado filtros de documento e phone

- frontend/src/components/Notificacao/Form/SinaisESintomas/SintomasGerais.vue
> fix #162 Apagando campo ao desmarcar Sintomático

- frontend/src/components/Notificacao/Form/IdentificacaoCaso/DadosPessoais.vue
- frontend/src/components/Notificacao/Form/IdentificacaoCaso/index.vue
- frontend/src/entities/Pessoa.js
- frontend/src/views/NotificacaoForm.vue
> fix #188 Máscara no cadastro de CPF

- frontend/src/views/NotificacaoExportar.vue
> Criado validação de período para exportação de excel #422

- backend/src/validations/schemas/notificacao.js
> melhoria na mensagem retornada da validação de telefone #207

- backend/.vscode/launch.json
- backend/src/models/pessoa.js
- backend/src/resource/notificacao-resource.js
- backend/src/validations/custom/document-validator.js
> Feature/validacao cpf suspeito #399

- backend/src/db/migrations/20200505174314-remover-campo-bairroId-notificacao.js
- backend/src/mapper/notificacao-mapper/request-para-model.js
- backend/src/models/notificacao.js
- backend/src/resource/notificacao-resource.js
> remoção da coluna bairroId e atualização do mapeamento da entidade 'Notificação' #434

- backend/src/mapper/notificacao-mapper/model-para-response.js
> correção no mapeamento do municipioId #449

- backend/src/db/migrations/20200506134926-create-user-unidade-saude.js
- backend/src/db/seeders/20200507122949-add-user-unidade-saude.js
- backend/src/models/userunidadesaude.js
- backend/src/resource/unidade-saude-resource.js
- backend/src/routes/unidade-saude-route.js
- frontend/src/components/Notificacao/Form/IdentificacaoNotificante/index.vue
- frontend/src/services/UnidadeSaudeService.js
- [backend:api] para consultar as unidades de saúde por e-mail do usuário.
- [front-end] Consultar as unidades de saúde com preenchimento automático.
- [front-end] Caso o usuário seja do perfil 'SECRETARIA', o mesmo tem a possibilidade de buscar outras unidades de saúde, caso contrário, não permite a busca.
> Feature/preenchimento unidade saude #221

- backend/src/db/seeders/20200507122949-add-user-unidade-saude.js
> correção seed para postgres #221

- frontend/entrypoint.sh
> #425 - Atualizando variaveis de ambiente do container

- backend/src/resource/notificacao-resource.js
> Alterar algoritmo que verifica se pessoa deve ser reutilizada ou gravada

- backend/src/db/seeders/20200507121313-add-unidade-goncalves.js
- backend/src/db/seeders/20200507122609-add-user-rosane-bresciani.js
> Adicionado scripts pra incluir usuário e unidade de saúde

- frontend/src/components/Notificacao/Form/IdentificacaoCaso/Contato.vue
> fix #150 UI - obrigatoriedade dos campos de telefone

- keycloak/standalone-ha.xml
> alterado nome base keycloak

- frontend/src/components/Notificacao/Form/IdentificacaoCaso/DadosPessoais.vue
> fix #188 limpando número do documento ao mudar o tipo do documento

- frontend/src/components/Notificacao/Form/ExamesImagem/TomografiaTorax.vue
- frontend/src/components/Notificacao/Form/ExamesImagem/index.vue
- frontend/src/views/NotificacaoForm.vue
> fix #156 limpando campos de raios e tomografia ao marcar não

- keycloak/Dockerfile
> atualizado variável proxy keycloak

- frontend/.env.dev
> voltado env apontando para o qa

- backend/.env.sample
- backend/.gitignore
- backend/src/mapper/notificacao-mapper/model-para-response.js
- backend/src/resource/notificacao-resource.js
4. [-] Você criou novos testes para o código escrito?
5. [-] Os testes foram rodados e passaram localmente?
> fixes #465 nao esta salvando sem enviar cpf

- backend/.gitignore
- terraform/frontend.tf
> Adicionado variável ambiente terraform

- frontend/src/components/Notificacao/Form/Comorbidades/index.vue
- frontend/src/components/Notificacao/Form/HistoricoDeViagem/index.vue
- frontend/src/components/Notificacao/Form/SinaisESintomas/OutrosSintomas.vue
> Limpado os campos "Especifique"

- frontend/src/components/Notificacao/Form/ContatoComSuspeitoOuConfirmado/index.vue
- frontend/src/components/Notificacao/Form/RealizadoColeta/index.vue
- frontend/src/views/NotificacaoForm.vue
> Correçao Data da coleta, nome da pessoa, centralização de mensagem

- frontend/src/components/Notificacao/Form/ContatoComSuspeitoOuConfirmado/index.vue
- frontend/src/components/Notificacao/Form/IdentificacaoCaso/DadosPessoais.vue
- frontend/src/components/Notificacao/Form/IdentificacaoCaso/Endereco.vue
- frontend/src/components/Notificacao/Form/IdentificacaoNotificante/index.vue
- frontend/src/validations/CommonValidations.js
- frontend/src/validations/__tests__/CommonValidations.spec.js
> Validação dos caracteres informados

- backend/src/secure/index.js
- terraform/backend.tf
> Fix keycloak to need token without login

- frontend/src/services/DownloadService.js
- frontend/src/services/NotificacaoService.js
- frontend/src/views/NotificacaoExportar.vue
> Fix exportar

- backend/src/resource/gera-excel-resource.js
- backend/src/resource/notificacao-exportacao-excel-resource.js
> Corrigido processamento de data na exportação da planilha de excel #453

- backend/src/resource/notificacao-exportacao-excel-resource.js
> Inserido ação para pegar informações do servidor

- frontend/src/components/Notificacao/Form/ConclusaoAtendimento/index.vue
> Colocando console.log na URL do PDF

- backend/src/resource/gera-excel-resource.js
> Corrigido formatação do período de exportação da planilha de excel #498

- backend/src/resource/notificacao-resource.js
> validação de cpf caso seja informado #489

- backend/src/secure/index.js
> alterado url keycloak padrão

- frontend/src/components/Notificacao/Evolucao/Cons.vue
- frontend/src/components/Notificacao/Evolucao/Form.vue
> Alteração de escrita na tela de evolução

- frontend/src/components/Notificacao/Form/IdentificacaoCaso/Contato.vue
- frontend/src/components/Notificacao/Form/IdentificacaoCaso/Endereco.vue
- frontend/src/components/Notificacao/Form/IdentificacaoCaso/Ocupacao.vue
- frontend/src/validations/CommonValidations.js
- frontend/src/validations/__tests__/CommonValidations.spec.js
> Validacao min length para telefone, campo complemento e descriçao da ocupaçao

- backend/src/resource/gera-excel-resource.js
- backend/src/resource/notificacao-exportacao-excel-resource.js
> Inserido exportação para o excel do campo Notificacao.createdAt #520

- frontend/src/views/EvolucaoForm.vue
- frontend/src/views/NotificacaoCons.vue
- frontend/src/views/NotificacaoForm.vue
> Centralizado mensagem de notificaçao e evoluçao salvo com sucesso

- frontend/src/components/Notificacao/Form/IdentificacaoCaso/Ocupacao.vue
> Remover termo técnico da mensagem

- frontend/src/router/index.js
> Barra de rolagem na visualização da notificação no meio da página

- frontend/src/components/Notificacao/Form/IdentificacaoCaso/DadosPessoais.vue
> Ajuste na mensagem do campo Número do documento, quando selecionado CPF

- backend/src/db/migrations/20200512143850-create-dm-localizacao.js
- backend/src/db/migrations/20200512144037-create-dm-paciente.js
- backend/src/db/migrations/20200512144354-create-fato-notificacao-covid-19.js
- backend/src/db/migrations/20200512144828-create-aprovacao-dados.js
- backend/src/models/aprovacaoDados.js
- backend/src/models/dmLocalizacao.js
- backend/src/models/dmPaciente.js
- backend/src/models/fatoNotificacaoCovid19.js
> Criado tabelas bases fatos - bi

- backend/src/services/consolidar-notificacao-atualizacao-service.js
> correção para validar novo documento adicionado no fluxo de atualização de notificação #431

- backend/src/resource/gera-excel-resource.js
- backend/src/resource/notificacao-exportacao-excel-resource.js
> Corrigido exportação de campo data gravado sem hora #543

- frontend/src/components/Notificacao/Evolucao/Form.vue
- frontend/src/components/Notificacao/Form/BotaoEnviar.vue
- frontend/src/views/NotificacaoForm.vue
> desabilitando o botão para request pendente 564

- backend/src/services/atualizar-notificacao-service.js
- frontend/src/components/Notificacao/Form/IdentificacaoCaso/DadosPessoais.vue
> validação da dataHora da notificação #568

- backend/src/services/atualizar-notificacao-service.js
- frontend/src/components/Notificacao/Consulta/NotificacaoTable/index.vue
> não permitir edição da notificação encerrada #559

- backend/src/validations/schemas/notificacao.js
- frontend/src/components/Notificacao/Form/HistoricoDeViagem/index.vue
> validação para que data da viagem seja menor ou igual a de hoje #547

- frontend/src/components/MainMenu/index.vue
- frontend/src/components/Notificacao/Consulta/HeaderCons/index.vue
> fix #561 Exigindo role SECRETARIA_SAUDE para mostrar botao de exportar

- frontend/src/entities/Sintomas.js
> fix #551 Campo decimal na temperatura

- backend/src/resource/notificacao-exportacao-excel-resource.js
> Retirado acentos do nome da coluna #553

- backend/src/enums/tipo-documento-enum.js
- backend/src/services/consolidar-notificacao-atualizacao-service.js
- frontend/src/components/Notificacao/Form/IdentificacaoCaso/DadosPessoais.vue
> Hotfix/edicao notificacao campo bloqueado #566 #567

- backend/src/repositories/notificacao-repository.js
- backend/src/services/atualizar-notificacao-service.js
> atualização evolução conforme notificação #577

- backend/src/validations/schemas/notificacao.js
> inserção do timezone na validação da data da viagem #547

- frontend/src/components/Notificacao/Form/SinaisESintomas/SintomasRespiratorios.vue
> Campo "Informar temperatura" não obrigatório.

- frontend/src/components/Notificacao/Form/IdentificacaoCaso/Ocupacao.vue
> Obrigatoriedade do campo "Descrição da ocupação".

- backend/src/lib/erros/UsuarioNaoAutorizadoErro.js
- backend/src/lib/erros/index.js
- backend/src/repositories/repository-factory.js
- backend/src/repositories/usuario-repository.js
- backend/src/resource/notificacao-resource.js
- backend/src/routes/notificacao-gera-excel-route.js
- frontend/src/views/NotificacaoExportar.vue
- frontend/src/views/NotificacaoForm.vue
> Hotfix/permissao ver notificacao #580

- backend/src/app.js
- backend/src/extensions/arrary-extensions.js
> validação dataHora notificação no contexto das evoluções #583

- backend/src/db/migrations/20200514121943-create-fechamento-notificacao-covid19.js
- backend/src/models/fechamentoNotificacaoCovid19.js
- backend/src/repositories/fechamento-notificacao-covid19-repository.js
- backend/src/repositories/repository-factory.js
- backend/src/resource/fechamento-notificacao-covid19-resource.js
- backend/src/routes/fechamento-notificacao-covid19-route.js
> Feature/fechamento notificacao #512

- backend/src/resource/fechamento-notificacao-covid19-resource.js
> Hotfix/correcao vwboletim fechamento #512

- backend/src/db/migrations/20200520190551-remocao-qtd-internado.js
- backend/src/db/migrations/20200520191248-remocao-qtd-confirmado-internado.js
- backend/src/models/fechamentoNotificacaoCovid19.js
- backend/src/resource/fechamento-notificacao-covid19-resource.js
> remoção da coluna qtdinternado #605

- backend/src/resource/fechamento-notificacao-covid19-resource.js
> consulta fechamentos por data #512

- backend/src/resource/fechamento-notificacao-covid19-resource.js
- backend/src/routes/fechamento-notificacao-covid19-route.js
- frontend/src/components/FechamentoDiario/ModalDetalhesFechamentoDiario.vue
- frontend/src/components/FechamentoDiario/index.vue
- frontend/src/entities/DetalhesFechamentoDiario.js
- frontend/src/services/FechamentoService.js
> Feature/detalhe fechamento notificacao #556

- backend/package.json
- backend/src/resource/fechamento-notificacao-covid19-resource.js
- backend/yarn.lock
- frontend/src/components/FechamentoDiario/ModalDetalhesFechamentoDiario.vue
- frontend/src/components/FechamentoDiario/index.vue
- frontend/src/components/MainMenu/index.vue
- frontend/src/services/FechamentoService.js
- frontend/src/views/FechamentoDiario.vue
> melhorias no fechamento

- backend/src/resource/fechamento-notificacao-covid19-resource.js
> corrigindo timestamp qa

- backend/src/resource/fechamento-notificacao-covid19-resource.js
> corrigindo timezone detalhes fechamento

- backend/config/config.js
- backend/src/resource/fechamento-notificacao-covid19-resource.js
- frontend/src/components/FechamentoDiario/index.vue
> alterado timezone para SP

- backend/src/app.js
> force define timezone SP

- backend/src/resource/fechamento-notificacao-covid19-resource.js
> change select to use inner join in details

- backend/src/resource/fechamento-notificacao-covid19-resource.js
- frontend/src/components/FechamentoDiario/ModalDetalhesFechamentoDiario.vue
- frontend/src/entities/DetalhesFechamentoDiario.js
> change details date to createdAt

- frontend/src/components/FechamentoDiario/ModalDetalhesFechamentoDiario.vue
> fix order details

- backend/src/mapper/notificacao-mapper/index.js
- backend/src/mapper/notificacao-mapper/model-para-response.js
- backend/src/models/notificacaoEvolucao.js
- backend/src/repositories/notificacao-repository.js
- backend/src/resource/notificacao-resource.js
- frontend/src/components/Notificacao/Evolucao/Cons.vue
- frontend/src/components/Notificacao/Form/Comorbidades/index.vue
- frontend/src/components/Notificacao/Form/IdentificacaoCaso/DadosPessoais.vue
- frontend/src/components/Notificacao/Form/IdentificacaoCaso/Endereco.vue
- frontend/src/components/Notificacao/Form/IdentificacaoCaso/index.vue
- frontend/src/entities/Notificacao.js
- frontend/src/entities/NotificacaoEvolucao.js
- frontend/src/services/DateService.js
- frontend/src/views/NotificacaoForm.vue
> Não permitir excluir evolução quando houver fechamento

- frontend/src/entities/NotificacaoEvolucao.js
- frontend/src/entities/__tests__/Evolucao.spec.js
- frontend/src/entities/__tests__/NotificacaoEvolucao.spec.js
- frontend/src/entities/__tests__/NotificacaoEvolucao2.spec.js
> fix testes

- backend/src/resource/fechamento-notificacao-covid19-resource.js
> fix order fechamento

- backend/src/db/scripts/20200601164214-create-view-reabrirfechamento-create.sql
- backend/src/lib/secureRealm.js
- backend/src/resource/fechamento-notificacao-covid19-resource.js
- backend/src/routes/fechamento-notificacao-covid19-route.js
- frontend/src/components/FechamentoDiario/index.vue
> melhorias reabertura fechamento

- backend/src/repositories/fechamento-notificacao-covid19-repository.js
- backend/src/resource/fechamento-notificacao-covid19-resource.js
> alterado reabrir para excluir o fechamento

- backend/src/db/scripts/20200601164214-create-view-reabrirfechamento-create.sql
> fix scrippt fechamento

- backend/src/db/migrations/20200601203119-add-descartado-fato.js
- backend/src/db/migrations/20200601203433-atualizar-views-fato.js
- backend/src/db/scripts/20200601203433-atualizar-views-fato-create.sql
- backend/src/models/fatoNotificacaoCovid19.js
> adicionado campo descartado fato

- backend/src/db/migrations/20200601151747-add-status-fechamento.js
- backend/src/db/migrations/20200601203119-add-descartado-fato.js
- backend/src/db/scripts/20200601164214-create-view-reabrirfechamento-create.sql
- backend/src/models/fechamentoNotificacaoCovid19.js
> melhorias status fechamento

- backend/src/db/migrations/20200602145054-add-descartado-fechamento.js
- backend/src/db/scripts/20200601203433-atualizar-views-fato-create.sql
- backend/src/models/fechamentoNotificacaoCovid19.js
- frontend/src/components/FechamentoDiario/index.vue
- frontend/src/entities/FechamentoDiario.js
> adicionado coluna descartados

- backend/src/resource/fechamento-notificacao-covid19-resource.js
> salvar descartados no fechamento

- frontend/src/entities/FechamentoDiario.js
> arrumado entidade fechamento

- backend/src/db/seeders/20200603123913-add-codigos-ibge.js
> atualizado seed para usar like no nome da cidade

- backend/src/resource/notificacao-resource.js
- backend/src/secure/roles.js
- backend/src/secure/usuario-logado.js
- frontend/src/components/Notificacao/Consulta/NotificacaoTable/index.vue
> adicionado perfil para visualizar todas notificacoes

- backend/src/db/scripts/20200601203433-atualizar-views-fato-create.sql
- backend/src/resource/gera-excel-notificacao-resource.js
- backend/src/resource/graficos-resource.js
- backend/src/routes/grafico-route.js
> melhorias api graficos e correção exportar excel

- backend/Dockerfile
- backend/entrypoint.sh
- backend/package.json
> adicionado suporte ao pm2

- frontend/src/components/Notificacao/Exportar/Index.vue
- frontend/src/services/DateService.js
- frontend/src/services/DownloadService.js
- frontend/src/views/NotificacaoExportar.vue
> travado download no período de 7 dias

- backend/src/resource/gera-excel-notificacao-resource.js
> adicionado campos no excel

- backend/src/resource/gera-excel-notificacao-resource.js
> alterado filtro para data de criação da notificação

- backend/src/resource/gera-excel-notificacao-resource.js
> melhorias geração do excel

- backend/.gitignore
- frontend/src/views/NotificacaoExportar.vue
> melhorias download excel

- backend/src/models/index.js
> melhorias pool conexao

- backend/src/resource/gera-excel-notificacao-resource.js
- frontend/src/views/NotificacaoExportar.vue
> melhoria download sem block

- backend/src/resource/gera-excel-notificacao-resource.js
- frontend/src/views/NotificacaoExportar.vue
> validando se o arquivo existe e aumentando timeout

- backend/src/resource/gera-excel-notificacao-resource.js
> alterado forma de verificar download

- backend/src/resource/gera-excel-notificacao-resource.js
> alterado validação do download

- backend/src/resource/gera-excel-notificacao-resource.js
> add timeout download

- backend/src/models/index.js
- backend/src/resource/gera-excel-notificacao-resource.js
- backend/src/resource/graficos-resource.js
- backend/src/routes/grafico-route.js
> melhorias download e grafico por dia

- frontend/src/views/NotificacaoExportar.vue
> aumentado tentativas de download

- backend/src/resource/fechamento-notificacao-covid19-resource.js
> alterado horário detalhes fechamento para as 15h

- backend/src/resource/gera-excel-notificacao-resource.js
> melhorias rotina download

- backend/src/models/index.js
- backend/src/resource/gera-excel-notificacao-resource.js
> corrigido definição do pool

- backend/src/resource/gera-excel-notificacao-resource.js
- backend/src/routes/notificacao-gera-excel-route.js
- frontend/src/services/NotificacaoService.js
- frontend/src/views/NotificacaoExportar.vue
> voltado mecanismo de download para ser sincrono

- backend/src/server.js
> adicionado log erros não capturados

- backend/entrypoint.sh
> aumentado memória do PM2 antes de reiniciar

- backend/entrypoint.sh
> aumentado memória heap antes de reiniciar

- .circleci/config.yml
- backend/entrypoint.sh
- terraform/backend.tf
> aumentado memória heap e do container

- backend/src/models/index.js
> alterado pool

- backend/src/resource/notificacao-resource.js
> corrigido data suspeito na notificação

- backend/src/db/migrations/20200620235733-add-leitos-unidade-saude.js
- backend/src/lib/secureRealm.js
- backend/src/models/municipio.js
- backend/src/models/unidadesaude.js
- backend/src/resource/gera-excel-notificacao-resource.js
- backend/src/resource/unidade-saude-resource.js
- backend/src/routes/unidade-saude-route.js
- backend/src/validations/schemas/index.js
- backend/src/validations/schemas/unidadeSaude.js
- frontend/src/App.vue
- frontend/src/components/MainMenu/index.vue
- frontend/src/components/UnidadeSaude/HeaderUnidadeSaude.vue
- frontend/src/components/UnidadeSaude/UnidadeSaudeForm.vue
- frontend/src/components/UnidadeSaude/UnidadeSaudeTable.vue
- frontend/src/entities/StateForm.js
- frontend/src/entities/UnidadeSaude.js
- frontend/src/router/index.js
- frontend/src/services/UnidadeSaudeService.js
- frontend/src/validations/CommonValidations.js
- frontend/src/views/UnidadeSaudeCons.vue
- frontend/src/views/UnidadeSaudeForm.vue
> Issue 70 - Cadastro de Unidades de Saúde

- backend/src/resource/unidade-saude-resource.js
> atualizado mensagem cnes unico

- frontend/src/components/MainMenu/index.vue
> atualizado menu unidade saude

- backend/package.json
- backend/run-redis.bat
- backend/src/app.js
- backend/src/redis/index.js
- backend/src/resource/fechamento-notificacao-covid19-resource.js
- backend/src/resource/graficos-resource.js
- backend/yarn.lock
> adicionado suporte a redis e cache nos graficos

- backend/src/redis/index.js
> criado reconexao redis

- backend/src/resource/gera-excel-notificacao-resource.js
- frontend/src/components/Notificacao/Exportar/Index.vue
- frontend/src/entities/NotificacaoExportar.js
- frontend/src/services/NotificacaoService.js
- frontend/src/validations/CommonValidations.js
- frontend/src/views/NotificacaoExportar.vue
> adicionado filtro por evolução e melhorado tela de exportação

- frontend/src/App.vue
- frontend/src/components/commons/UnidadeHeader.vue
- frontend/src/views/Home.vue
> Melhorias menu e home

- backend/config/config.js
> fix config database

- backend/src/db/migrations/20200706181449-add-views-perfil-suspeito.js
- backend/src/db/scripts/20200706181449-add-views-perfil-suspeito-create.sql
- backend/src/db/scripts/20200706181449-add-views-perfil-suspeito-drop.sql
- backend/src/resource/notificacao-secretaria-saude-resource.js
- backend/src/services-api/secretaria-saude/service.js
> melhorias integração api e api sexo/idade

- frontend/src/components/MainMenu/index.vue
> Feat api suspeitos

- frontend/src/components/MainMenu/index.vue
- terraform/backend.tf
> liberado menu envio secretaria

- backend/src/lib/erros/api-error-handling.js
- backend/src/services-api/keycloak/auth/index.js
> melhorias keycloak auth

- backend/src/services-api/keycloak/auth/index.js
- frontend/src/components/Usuario/UsuarioForm.vue
> Feat users

- backend/src/secure/index.js
> add props keycloak

- backend/src/services-api/keycloak/users/index.js
> retornado todos usuários

- backend/src/services-api/secretaria-saude/service.js
> melhoria tratamento de erros envio secretaria

- backend/src/secure/index.js
> removido propriedades keycloak

- backend/src/resource/notificacao-secretaria-saude-resource.js
- backend/src/services-api/secretaria-saude/enums/api-errors.js
- backend/src/services-api/secretaria-saude/service.js
> melhorias envio api

- backend/src/lib/erros/api-error-handling.js
- backend/src/validations/schemas/notificacao.js
- frontend/src/components/ControleLeitoPerfil/ControleLeitoPerfilTable.vue
- frontend/src/components/ControleLeitos/ControleLeitosForm.vue
- frontend/src/components/ControleLeitos/ControleLeitosTable.vue
- frontend/src/components/EnvioSecretaria/index.vue
- frontend/src/components/FechamentoDiario/ModalDetalhesFechamentoDiario.vue
- frontend/src/components/FechamentoDiario/index.vue
- frontend/src/components/Notificacao/Consulta/NotificacaoTable/index.vue
- frontend/src/components/Notificacao/Evolucao/Cons.vue
- frontend/src/components/Notificacao/Evolucao/Form.vue
- frontend/src/components/UnidadeSaude/UnidadeSaudeForm.vue
- frontend/src/components/UnidadeSaude/UnidadeSaudeTable.vue
- frontend/src/components/Usuario/UsuarioForm.vue
- frontend/src/components/Usuario/UsuarioTable.vue
- frontend/src/entities/UnidadeSaude.js
- frontend/src/services/ErrorService.js
- frontend/src/views/NotificacaoCons.vue
- frontend/src/views/NotificacaoForm.vue
> fix data viagem e mensagens de erro

- backend/src/lib/erros/api-error-handling.js
- backend/src/services-api/secretaria-saude/models/enviar-notificacao-request.js
- frontend/src/components/EnvioSecretaria/index.vue
> corrigido envio para secretaria

- frontend/src/services/ErrorService.js
> alterado console.info ao pegar mensagem de erro

- backend/src/lib/erros/api-error-handling.js
- backend/src/repositories/notificacao-repository.js
- backend/src/resource/notificacao-secretaria-saude-resource.js
- backend/src/routes/notificacoes-secretaria-route.js
- backend/src/routes/notification-route.js
- backend/src/services-api/secretaria-saude/service.js
- frontend/src/services/ErrorService.js
> implementação da rotina de sincronização de notificações

- backend/src/resource/notificacao-secretaria-saude-resource.js
> Feat atualizar envio

- backend/src/repositories/notificacao-repository.js
- backend/src/resource/notificacao-secretaria-saude-resource.js
> adicionado limite na consulta de sincronização

- backend/src/repositories/notificacao-repository.js
- backend/src/resource/notificacao-secretaria-saude-resource.js
> adicionado paginacao na consulta de sincronização

- backend/src/repositories/notificacao-repository.js
- backend/src/resource/notificacao-secretaria-saude-resource.js
> adicionado count total na consulta de sincronização

- frontend/src/services/ErrorService.js
> adicionado nova opção de mensagem de erro

- backend/src/resource/notificacao-secretaria-saude-resource.js
> logado resposta do envio a secretaria

- backend/src/resource/notificacao-secretaria-saude-resource.js
- backend/src/services-api/secretaria-saude/enums/api-errors.js
> ao atualizar caso retorne id marcar como enviado

- backend/src/services-api/secretaria-saude/models/enviar-notificacao-request.js
> corrigido assintomatico

- backend/src/services-api/secretaria-saude/models/enviar-notificacao-request.js
> alterado datas e assintomatico

- backend/src/resource/notificacao-secretaria-saude-resource.js
- backend/src/services-api/secretaria-saude/enums/api-errors.js
> atualizado quando notificação esta encerrada na secretaria

- backend/src/resource/notificacao-secretaria-saude-resource.js
> retornado mensagem id da resposta da atualizacao

- backend/src/resource/notificacao-secretaria-saude-resource.js
- backend/src/services-api/secretaria-saude/models/enviar-notificacao-request.js
- frontend/src/components/EnvioSecretaria/index.vue
- frontend/src/services/ErrorService.js
> corrigido código pais extrangeiro

- backend/src/services-api/secretaria-saude/service.js
> desabilitado o ssl momentaneamente

- backend/src/resource/notificacao-secretaria-saude-resource.js
> alterado log resultado envio secretaria

- backend/package.json
- backend/src/lib/erros/api-error-handling.js
- backend/src/lib/secureRealm.js
- backend/src/resource/notificacao-evolucao-resource.js
- backend/src/routes/fechamento-notificacao-covid19-route.js
- backend/src/routes/notificacoes-secretaria-route.js
- backend/src/routes/notification-route.js
- backend/src/secure/roles.js
- backend/src/secure/usuario-logado.js
- backend/src/services-api/secretaria-saude/service.js
- backend/src/validations/schemas/evolucao.js
- backend/src/validations/schemas/index.js
- backend/yarn.lock
- frontend/src/components/FechamentoDiario/index.vue
- frontend/src/components/MainMenu/index.vue
- frontend/src/components/Notificacao/Evolucao/Cons.vue
- frontend/src/services/ErrorService.js
- frontend/src/services/EvolucaoService.js
- frontend/src/views/EvolucaoForm.vue
- terraform/backend.tf
> adicionado novas permisões e possibilidade de alterar a data da evolucao

- backend/src/repositories/notificacao-repository.js
- backend/src/resource/notificacao-resource.js
- backend/src/resource/notificacao-secretaria-saude-resource.js
- backend/src/services-api/secretaria-saude/models/enviar-notificacao-request.js
- frontend/src/components/EnvioSecretaria/index.vue
> melhorias envio secretaria e assintomatico

- backend/src/services-api/secretaria-saude/models/enviar-notificacao-request.js
> alterado sintomatico para false caso seja nulo

- frontend/src/entities/Pessoa.js
> alterado pais padrão ser Brasil

- backend/src/models/index.js
> alterado configurações pool sequelize

- backend/src/services-api/secretaria-saude/service.js
> alterado barra rota envio

- backend/src/mapper/notificacao-mapper/consulta.js
- backend/src/models/notificacaoCovid19.js
- backend/src/models/unidadesaude.js
- backend/src/resource/notificacao-resource.js
- backend/src/services-api/secretaria-saude/models/enviar-notificacao-request.js
- backend/src/validations/schemas/notificacao.js
- frontend/src/components/Notificacao/Consulta/NotificacaoTable/index.vue
- frontend/src/components/Notificacao/Evolucao/Cons.vue
- frontend/src/components/Notificacao/Evolucao/Form.vue
- frontend/src/components/Notificacao/Form/ContatoComSuspeitoOuConfirmado/index.vue
- frontend/src/components/Notificacao/Form/HistoricoDeViagem/index.vue
- frontend/src/components/Notificacao/Form/Hospitalizacao/index.vue
- frontend/src/components/Notificacao/Form/IdentificacaoCaso/DadosPessoais.vue
- frontend/src/components/Notificacao/Form/InformacoesComplementares/index.vue
- frontend/src/components/Notificacao/Form/RealizadoColeta/index.vue
- frontend/src/components/Notificacao/Form/VinculoEpidemiologico/index.vue
- frontend/src/components/UnidadeSaude/UnidadeSaudeForm.vue
- frontend/src/entities/NotificacaoConsulta.js
- frontend/src/validations/CommonValidations.js
- frontend/src/views/NotificacaoCons.vue
> melhorias notificação, consulta e evolução

- backend/src/services-api/secretaria-saude/models/enviar-notificacao-request.js
> alterado critérios de classificação

- backend/src/services-api/secretaria-saude/models/enviar-notificacao-request.js
> corrigido sexo do paciente no envio

- frontend/src/components/Notificacao/Form/RealizadoColeta/index.vue
> alterado regra de data recebimento maior q coleta

- backend/src/services-api/secretaria-saude/models/enviar-notificacao-request.js
- frontend/src/components/Notificacao/Consulta/NotificacaoTable/index.vue
- frontend/src/components/Notificacao/Form/RealizadoColeta/index.vue
> removido exames e resultados

- frontend/src/entities/Sintomas.js
- frontend/src/views/NotificacaoForm.vue
> fix limpar sintomas ao desmarcar sintomatico

- backend/src/services-api/secretaria-saude/models/dicionario-valores.js
- backend/src/services-api/secretaria-saude/models/enviar-notificacao-request.js
> correção gestante alto risco

- backend/src/services-api/secretaria-saude/models/enviar-notificacao-request.js
> tratamento de campos inteiros no envio

- backend/src/models/tenantConfig.js
> fix email tenant

- backend/run-redis-cli.bat
- backend/src/resource/user-resource.js
- backend/src/routes/users-route.js
> segurança api usuário

- frontend/src/entities/NotificacaoExportar.js
- frontend/src/services/NotificacaoService.js
- frontend/src/views/NotificacaoExportar.vue
> Multi tentant

- frontend/src/components/Notificacao/Exportar/Index.vue
- frontend/src/views/NotificacaoExportar.vue
> removido exportação por excel

- backend/src/repositories/exporta-notificacao-repository.js
- backend/src/resource/exportar-notificacoes.js
> adicionado campos exportação, cobormidade e data confirmado evolucao

- backend/src/resource/exportar-notificacoes.js
> melhorias geração csv

- backend/src/models/aprovacaoDado.js
- backend/src/repositories/fechamento-repository.js
> adicionado aprovação de dados por municipio

- backend/src/resource/exportar-notificacoes.js
> melhorias download

- backend/src/resource/exportar-notificacoes.js
> alterado células csv para comportar virgula e quebra de linha

- backend/src/repositories/fato-repository.js
> corrigido acompanhamento fechamento indicadores

- backend/src/resource/exportar-notificacoes.js
> replace quote no csv, evitar quebra no libreoffice

- backend/src/repositories/fechamento-repository.js
- backend/src/repositories/notificacao-repository.js
> corrigido fechamento e reabertura das datas de evolução na notificacao

- backend/src/repositories/notificacao-repository.js
- backend/src/resource/fechamento-resource.js
> melhorias paginação e consulta fechamento detalhes

- backend/src/repositories/notificacao-repository.js
> adicionado filtro na consulta do count detalhes fechamento

- backend/src/repositories/fechamento-repository.js
- backend/src/resource/graficos-resource.js
- backend/src/routes/grafico-route.js
> adicionado rotas da média movel

- backend/src/services-api/secretaria-saude/models/enviar-notificacao-request.js
- frontend/src/components/Notificacao/Form/SinaisESintomas/SintomasRespiratorios.vue
> removido obrigatoriedade da temperatura

- frontend/src/components/Notificacao/Form/RealizadoColeta/index.vue
> resultado obrigatorio quando definido o exame

- backend/src/resource/graficos-resource.js
- backend/src/routes/grafico-route.js
> alterado para trazer todos os fechamentos

- backend/src/db/migrations/20200901195415-add-dataobito-notificacaocovid.js
- backend/src/mapper/notificacao-mapper/model-para-response.js
- backend/src/models/notificacaoCovid19.js
- backend/src/services/atualizar-notificacao-service.js
- backend/src/validations/schemas/notificacao.js
- frontend/src/components/Notificacao/Consulta/NotificacaoTable/index.vue
- frontend/src/components/Notificacao/Form/ConclusaoAtendimento/index.vue
- frontend/src/components/Notificacao/Form/Hospitalizacao/index.vue
- frontend/src/entities/ConclusaoAtendimento.js
- frontend/src/entities/Hospitalizacao.js
- frontend/src/views/NotificacaoForm.vue
> melhorias atualização hospitalização

- backend/src/db/migrations/20200903181740-add-dtencerramento-notifcovid.js
- backend/src/db/seeders/20200903184436-update-notificacao-encerramento.js
- backend/src/mapper/notificacao-mapper/model-para-response.js
- backend/src/mapper/notificacao-mapper/request-para-model.js
- backend/src/models/notificacao.js
- backend/src/repositories/notificacao-covid19-repository.js
- backend/src/repositories/notificacao-repository.js
- backend/src/resource/notificacao-evolucao-resource.js
- backend/src/resource/notificacao-resource.js
- backend/src/resource/notificacao-secretaria-saude-resource.js
- backend/src/routes/notificacoes-secretaria-route.js
- backend/src/services-api/secretaria-saude/enums/api-errors.js
- backend/src/services-api/secretaria-saude/models/enviar-notificacao-request.js
- backend/src/services-api/secretaria-saude/service.js
- backend/src/services/atualizar-notificacao-service.js
- backend/src/services/cadastrar-notificacao-evolucao-service.js
- backend/src/validations/schemas/notificacao.js
- frontend/src/components/EnvioSecretaria/index.vue
- frontend/src/components/Notificacao/Consulta/NotificacaoTable/index.vue
- frontend/src/components/Notificacao/Form/IdentificacaoCaso/DadosPessoais.vue
- frontend/src/components/Notificacao/Form/IdentificacaoCaso/index.vue
- frontend/src/entities/Notificacao.js
- frontend/src/entities/NotificacaoPendenteEnvioSecretaria.js
- frontend/src/services/NotificacaoPendenteEnvioService.js
- frontend/src/views/NotificacaoForm.vue
> permitir atualizar notificação

- frontend/src/components/Notificacao/Form/IdentificacaoCaso/DadosPessoais.vue
> desabilitado data encerramento

- backend/src/resource/notificacao-resource.js
- backend/src/services/atualizar-notificacao-service.js
> alterado para encerrar apenas pelas evoluções

- frontend/src/components/Notificacao/Form/IdentificacaoCaso/Contato.vue
> removido telefone contato e tornado celular obrigatório

- backend/src/resource/notificacao-secretaria-saude-resource.js
> fix envio notificação para todas pessoas

- backend/src/resource/user-resource.js
- frontend/src/components/Usuario/UsuarioForm.vue
> corrigido problema com permissões de usuário

- backend/src/resource/graficos-resource.js
> criado mecanismo para evitar sobrecarga no cache das cards

- backend/src/lib/secureRealm.js
- backend/src/routes/users-route.js
> melhoria permissões usuários

- backend/src/resource/user-resource.js
> removido cache chave roles usuário

- frontend/src/components/Notificacao/Evolucao/Cons.vue
* [S ] Você chegou a criar a issue antes de fazer o PR?
1. [x ] Sua submissão passou nos testes?
2. [x ] Seu código está de acordo com o lint do projeto?
5. [x ] Os testes foram rodados e passaram localmente?
Close #850
> SGSWBNOT-3:Botão para copiar o número do documento

- backend/src/services-api/secretaria-saude/models/enviar-notificacao-request.js
enviando para o estado evolucões DESCARTADO/ENCERRADO como CURA. Close #852
> SGSWBNOT-4: descartado/encerrado como cura

- backend/src/repositories/fechamento-repository.js
- backend/src/resource/fechamento-notificacao-covid19-resource.js
- backend/src/resource/graficos-resource.js
- backend/src/routes/grafico-route.js
> SGSWBNOT-6:endpoint para dados do grafico por faixa etária

- backend/src/db/migrations/20210126180930-create-taxa.js
- backend/src/models/taxa.js
- backend/src/repositories/repository-factory.js
- backend/src/repositories/taxa-repository.js
- backend/src/resource/taxa-resource.js
- backend/src/routes/taxa-route.js
- backend/src/validations/schemas/index.js
- backend/src/validations/schemas/taxa.js
- frontend/src/components/FechamentoDiario/index.vue
- frontend/src/entities/Taxa.js
- frontend/src/router/index.js
- frontend/src/services/TaxaService.js
- frontend/src/views/Taxas.vue
> Sgswbnot 8/informar taxa positivade ocupacao

- frontend/src/components/Notificacao/Form/RealizadoColeta/index.vue
> alterado de select para autocomplete

- backend/src/resource/graficos-resource.js
- backend/src/routes/grafico-route.js
> criado novo endpoint de graficos de resultado dos testes covid

- backend/src/resource/graficos-resource.js
> alterado consulta grafico resultado testes para semanas

- backend/src/resource/graficos-resource.js
- backend/src/routes/grafico-route.js
> adicionado rota graficos obitos

- frontend/src/services/__tests__/DateService.spec.js
> fix test DateService

- backend/src/app.js
> fix problem cors pre-flight
